### ISSUE TITLE
Figure out an optimal way for sorting threads by updated_at time

### ISSUE THREAD

**Issue by akinsey** [epochtalk/core#1]
Threads in the by board view should be sorted by updated_at not by creation time.

**Comment by akinsey** [comment]
### Notes on Thread index for sorting by last updated time
- (key) thread_by_updated ~ board_id ~ updated.timestamp ~ thread_id
- (value) thread_id

**Comment by taesup** [comment]
Completed in commit: eba86da6a94e7763d4a9b35c80c8a52dfdf9b315
