### ISSUE TITLE
Imports with Deleted or Unknown Authors

### ISSUE THREAD

**Issue by wangbus** [epochtalk/core#21]
For example: SMF imports with ID_MEMBER = 0 which means that the user is unknown. This is a design decision of how things should be handled.

**Comment by unenglishable** [comment]
The agreed solution was to add a "deleted" user on import with ID_MEMBER = -1.  This way, there are no hassles with checking the value for truthiness (-1 is not falsy, 0 is).

Furthermore, ID_MEMBER values in smf_messages are converted from 0 to -1 before streaming to epochcore.

Solved by https://github.com/epochtalk/importer-smf/commit/9b58ef97eff84bc0c73d4039be2c3280eddab785
